Repository gazebosim/gz-launch, pull requests merged in 2020-09, with the labels that each got.

#58 1 ➡️ 2
  Changelog.md
  examples/factory.ign
  examples/websocket.ign
  plugins/websocket_server/WebsocketServer.cc
Labels: 🏰 citadel

#59 2 ➡️ 3
  .gitignore
  CMakeLists.txt
  Changelog.md
  README.md
  api.md.in
  codecov.yml
  examples/factory.ign
  examples/gazebo_plugins.ign
  examples/multi_factory.ign
  examples/plugins.ign
  examples/websocket.ign
  plugins/gazebo_factory/GazeboFactory.cc
  plugins/gazebo_factory/GazeboFactory.hh
  plugins/gazebo_gui/GazeboGui.cc
  plugins/gazebo_gui/GazeboGui.hh
  plugins/gazebo_server/GazeboServer.cc
  plugins/gazebo_server/GazeboServer.hh
  plugins/joy_to_twist/JoyToTwist.hh
  plugins/joystick/Joystick.hh
  plugins/websocket_server/CMakeLists.txt
  plugins/websocket_server/MessageDefinitions.hh.in
  plugins/websocket_server/README.md
  plugins/websocket_server/WebsocketServer.cc
  plugins/websocket_server/WebsocketServer.hh
  plugins/websocket_server/combined.proto
  plugins/websocket_server/eventemitter2.min.js
  plugins/websocket_server/gz3d.js
  plugins/websocket_server/ign.js
  plugins/websocket_server/index-old.html
  plugins/websocket_server/index.html
  plugins/websocket_server/localhost.cert
  plugins/websocket_server/localhost.key
  tutorials.md.in
  tutorials/tutorial.md
Labels: beta, 🔮 dome

#57 Use random name for manager semaphore
  src/CMakeLists.txt
  src/Manager.cc
Labels: 📜 blueprint

#54 Add support for specifying topics to record
  CMakeLists.txt
  plugins/gazebo_server/GazeboServer.cc
Labels: 📜 blueprint
