Repository gazebosim/gz-launch, pull requests merged in 2020-12, with the labels that each got.

#76 3 to main 30112020
  Changelog.md
Labels: 🏢 edifice

#78 3.1.0 release prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#79 ⬆️ 1.10.1 🏁
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint
