Repository gazebosim/gz-launch, pull requests merged in 2020-08, with the labels that each got.

#39 Update Dome versions
  .github/ci-bionic/dependencies.yaml
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  bitbucket-pipelines.yml
  src/vendor/backward.hpp
Labels: 🔮 dome

#42 Modernize actions CI
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
Labels: 📜 blueprint

#47 Remove the `lib`+`.so` from the plugin's name
  examples/factory.ign
  examples/gazebo_plugins.ign
  examples/multi_factory.ign
  examples/plugins.ign
  examples/websocket.ign
  plugins/gazebo_factory/GazeboFactory.hh
  plugins/gazebo_gui/GazeboGui.hh
  plugins/gazebo_server/GazeboServer.hh
  plugins/joy_to_twist/JoyToTwist.hh
  plugins/joystick/Joystick.hh
  plugins/websocket_server/WebsocketServer.hh
Labels: 🏰 citadel

#49 Websocket server metrics endpoint
  Changelog.md
  examples/websocket.ign
  plugins/websocket_server/WebsocketServer.cc
Labels: 📜 blueprint

#50 1.9.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#45 1 ➡️ 2
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  .gitignore
  Changelog.md
  examples/websocket.ign
  plugins/websocket_server/CMakeLists.txt
  plugins/websocket_server/MessageDefinitions.hh.in
  plugins/websocket_server/README.md
  plugins/websocket_server/WebsocketServer.cc
  plugins/websocket_server/WebsocketServer.hh
  plugins/websocket_server/combined.proto
  plugins/websocket_server/eventemitter2.min.js
  plugins/websocket_server/gz3d.js
  plugins/websocket_server/ign.js
  plugins/websocket_server/index-old.html
  plugins/websocket_server/index.html
  plugins/websocket_server/localhost.cert
  plugins/websocket_server/localhost.key
Labels: 🏰 citadel

#44 Add PKGCONFIG information to ignition-tools ign_find_package
  CMakeLists.txt
Labels: 🔮 dome

#51 👩‍🌾 [Backport] Add PKGCONFIG information to ignition-tools ign_find_package (#44)
  CMakeLists.txt
Labels: 📜 blueprint

#52 👩‍🌾 [Backport] Add PKGCONFIG information to ignition-tools ign_find_package (#44)
  CMakeLists.txt
Labels: 🏰 citadel

#48 Ign- launch tutorial
  tutorials/tutorial.md
Labels: 🏰 citadel

#55 Issue 46
  examples/factory.ign
Labels: 🔮 dome
