Repository gazebosim/gz-launch, pull requests merged in 2020-05, with the labels that each got.

#25 [ign-launch1] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  bitbucket-pipelines.yml
  codecov.yml
Labels: 📜 blueprint

#27 [ign-launch2] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  bitbucket-pipelines.yml
  codecov.yml
Labels: 🏰 citadel

#28 [master] Workflow updates
  .github/CODEOWNERS
  .github/ci-bionic/dependencies.yaml
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 🔮 dome

#19 Use the new GUI API of ign-gazebo
  CMakeLists.txt
  Changelog.md
  examples/gazebo_plugins.ign
  plugins/gazebo_gui/GazeboGui.cc
  plugins/gazebo_gui/GazeboGui.hh
Labels: 📜 blueprint

#20 Start of docs update
  CMakeLists.txt
  api.md.in
  tutorials.md.in
Labels: 📜 blueprint

#29 Prepare for 1.4.2 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#30 Multi spawn
  CMakeLists.txt
  Changelog.md
  examples/factory.ign
  examples/multi_factory.ign
  plugins/gazebo_factory/GazeboFactory.cc
  plugins/gazebo_factory/GazeboFactory.hh
Labels: 📜 blueprint
