Repository gazebosim/gz-launch, pull requests merged in 2020-11, with the labels that each got.

#69 Bump in edifice: ign-rendering5
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
Labels: 🏢 edifice

#70 Resolve updated codecheck issues
  src/Manager.cc
  test/integration/plugins/bad_plugins.hh
Labels: 📜 blueprint

#71 1 to 2
  Changelog.md
  plugins/gazebo_server/GazeboServer.cc
  plugins/websocket_server/WebsocketServer.cc
  src/CMakeLists.txt
  src/Manager.cc
  test/integration/plugins/bad_plugins.hh
Labels: 🏰 citadel

#65 2.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#75 2 to 3 30112020
  Changelog.md
Labels: 🔮 dome
