Repository gazebosim/gz-launch, pull requests merged in 2021-06, with the labels that each got.

#116 Extend websocket server to support message limits and throttling
  plugins/websocket_server/WebsocketServer.cc
  plugins/websocket_server/WebsocketServer.hh
Labels: 🔮 dome

#117 3 4 0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#119 Remove unused includes (fix build)
  plugins/gazebo_gui/GazeboGui.cc
Labels: 🏯 fortress
