Repository gazebosim/gz-launch, pull requests merged in 2021-01, with the labels that each got.

#81 Fix env parsing by placing it before executable parsing
  src/Manager.cc
  src/Manager_TEST.cc
Labels: 🔮 dome

#83 2 to 3 20210108
  src/Manager.cc
  src/Manager_TEST.cc
Labels: 🔮 dome

#84 Prep for 2.2.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#85 3.1.1 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#86 Bump in edifice: ign-msgs7
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
Labels: 🏢 edifice

#87 Bump in edifice: sdformat11 and ign-physics4
  .github/ci/packages.apt
  bitbucket-pipelines.yml
Labels: 🏢 edifice
