Repository gazebosim/gz-launch, pull requests merged in 2021-05, with the labels that each got.

#112 Convert depth and thermal image data to RGB before sending over websockets
  CMakeLists.txt
  plugins/websocket_server/WebsocketServer.cc
Labels: 🔮 dome

#114 Prepare for 3.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#113 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#115 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cppcheck.suppress.in
  tools/cppcheck_rules/header_guard.rule
  tools/cppcheck_rules/isinf_namespace.rule
  tools/cppcheck_rules/namespace_AZ.rule
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
Labels: 🏰 citadel
