Repository gazebosim/gz-launch, pull requests merged in 2021-03, with the labels that each got.

#93 Treat IGN_LAUNCH_CONFIG_PATH as a path list.
  Migration.md
  src/cmdlaunch.rb.in
  tutorials.md.in
  tutorials/tutorial.md
Labels: 🏰 citadel

#100 2 ➡️ 3
  .github/workflows/ci.yml
  Migration.md
  README.md
  bitbucket-pipelines.yml
  plugins/websocket_server/WebsocketServer.hh
  src/cmdlaunch.rb.in
  tutorials.md.in
  tutorials/tutorial.md
Labels: 🔮 dome

#101 3 ➡️ 4
  .github/workflows/ci.yml
  Changelog.md
  Migration.md
  README.md
  bitbucket-pipelines.yml
  plugins/websocket_server/WebsocketServer.hh
  src/Manager.cc
  src/Manager_TEST.cc
  src/cmdlaunch.rb.in
  tutorials.md.in
  tutorials/tutorial.md
Labels: beta, 🏢 edifice

#103 🎈 4.0.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice
