Repository gazebosim/gz-launch, pull requests merged in 2022-07, with the labels that each got.

#170 ign -> gz Shared Lib Migration : gz-launch
  Changelog.md
  Migration.md
  README.md
  examples/factory.ign
  examples/ls.ign
  examples/multi_factory.ign
  examples/plugins.ign
  examples/sim.ign
  examples/sim_plugins.ign
  examples/websocket.ign
  plugins/CMakeLists.txt
  plugins/sim_factory/CMakeLists.txt
  plugins/sim_factory/SimFactory.cc
  plugins/sim_factory/SimFactory.hh
  plugins/sim_gui/CMakeLists.txt
  plugins/sim_gui/SimGui.cc
  plugins/sim_gui/SimGui.hh
  plugins/sim_server/CMakeLists.txt
  plugins/sim_server/SimServer.cc
  plugins/sim_server/SimServer.hh
  src/Manager.cc
  src/Manager_TEST.cc
  test/config/echo.ign
  test/config/erb.ign
  test/config/ls.ign
  test/integration/faulty_plugins.cc
  tutorials/tutorial.md
Labels: needs upstream release, 🌱 garden, ign to gz

#178 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, QA

#180 2 ➡️ 5
  CMakeLists.txt
  README.md
  src/cmd/CMakeLists.txt
  src/cmd/ign_TEST.cc
  src/cmd/launch.bash_completion.sh
Labels: 🏯 fortress

#181 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
Labels: needs upstream release, ign to gz

#179 Add code coverage ignore file
  CMakeLists.txt
  coverage.ignore.in
Labels: 🏰 citadel, QA

#184 Merge ign-launch1 ➡️ ign-launch2
  CMakeLists.txt
  Changelog.md
  api.md.in
  tutorials.md.in
Labels: 🏰 citadel

#185 Merge ign-launch2 ➡️ ign-launch5
  CMakeLists.txt
  Changelog.md
  api.md.in
  coverage.ignore.in
  tutorials.md.in
Labels: 🏯 fortress
