Repository gazebosim/gz-launch, pull requests merged in 2022-06, with the labels that each got.

#165 ign -> gz Environment Variable Migration : gz-launch
  Migration.md
  src/cmd/launch_main.cc
Labels: 🌱 garden, ign to gz

#167 Bash completion for flags
  CMakeLists.txt
  src/CMakeLists.txt
  src/ign_TEST.cc
  src/launch.bash_completion.sh
Labels: 🏰 citadel, OOBE 📦✨

#171 [ign -> gz] CMake functions
  CMakeLists.txt
  include/gz/launch/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/launch.yaml.in
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#166 ign -> gz Upstream Macro Migration : gz-launch
  Migration.md
  plugins/gazebo_factory/GazeboFactory.cc
  plugins/gazebo_factory/GazeboFactory.hh
  plugins/gazebo_gui/GazeboGui.cc
  plugins/gazebo_gui/GazeboGui.hh
  plugins/gazebo_server/GazeboServer.hh
  plugins/joy_to_twist/JoyToTwist.hh
  plugins/joystick/Joystick.hh
  plugins/websocket_server/WebsocketServer.cc
  plugins/websocket_server/WebsocketServer.hh
  plugins/websocket_server/ign.js
  plugins/websocket_server/index.html
  src/Manager.cc
  src/cmd/ign.cc
  src/cmd/ign.hh
  src/cmd/launch_main.cc
  test/integration/plugins/bad_plugins.cc
Labels: needs upstream release, 🌱 garden, ign to gz

#169 ign -> gz CLI Migration : gz-launch
  Changelog.md
  README.md
  examples/gazebo.ign
  examples/gazebo_plugins.ign
  examples/plugins.ign
  plugins/websocket_server/README.md
  plugins/websocket_server/WebsocketServer.hh
  src/cmd/CMakeLists.txt
  src/cmd/gz.cc
  src/cmd/gz.hh
  src/cmd/gz_TEST.cc
  src/cmd/launch_main.cc
  tutorials/tutorial.md
Labels: needs upstream release, 🌱 garden, ign to gz

#172 Detect gz program instead of using CMake module to check for gz-tools
  CMakeLists.txt
  src/cmd/CMakeLists.txt
Labels: 🌱 garden

#168 Rename CMake project to gz
  CMakeLists.txt
  Changelog.md
  plugins/gazebo_factory/CMakeLists.txt
  plugins/gazebo_factory/GazeboFactory.hh
  plugins/gazebo_gui/CMakeLists.txt
  plugins/gazebo_gui/GazeboGui.hh
  plugins/gazebo_server/CMakeLists.txt
  plugins/gazebo_server/GazeboServer.hh
  plugins/joy_to_twist/CMakeLists.txt
  plugins/joy_to_twist/JoyToTwist.hh
  plugins/joystick/CMakeLists.txt
  plugins/joystick/Joystick.hh
  plugins/websocket_server/CMakeLists.txt
  plugins/websocket_server/README.md
  plugins/websocket_server/WebsocketServer.hh
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  test/integration/plugins/CMakeLists.txt
Labels: needs upstream release, 🌱 garden, ign to gz
