Repository gazebosim/gz-launch, pull requests merged in 2022-08, with the labels that each got.

#186 Merge ign-launch5 ➡️ main
  CMakeLists.txt
  Changelog.md
  README.md
  coverage.ignore.in
  plugins/websocket_server/WebsocketServer.cc
  plugins/websocket_server/WebsocketServer.hh
  src/cmd/CMakeLists.txt
  src/cmd/gz_TEST.cc
  src/cmd/launch.bash_completion.sh
Labels: 🌱 garden

#190 ign -> gz : Remove redundant namespace references
  plugins/gazebo_factory/GazeboFactory.cc
  plugins/gazebo_gui/GazeboGui.cc
  plugins/gazebo_server/GazeboServer.cc
  plugins/joy_to_twist/JoyToTwist.cc
  plugins/joystick/Joystick.cc
Labels: 🏰 citadel, ign to gz

#188 Migrate config and log directories
  README.md
Labels: 🌱 garden, ign to gz

#192 🎈 2.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#193 🎈 5.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#196 Fix usage of message headers
  plugins/joy_to_twist/JoyToTwist.cc
  plugins/joy_to_twist/JoyToTwist.hh
  plugins/joystick/Joystick.cc
  plugins/sim_factory/SimFactory.cc
  plugins/sim_server/SimServer.cc
  plugins/websocket_server/WebsocketServer.cc
Labels: bug, 🌱 garden
