Repository gazebosim/gz-launch, pull requests merged in 2023-09, with the labels that each got.

#229 Remove focal github actions
  .github/workflows/ci.yml
Labels: 🎵 harmonic

#230 Update installation instructions based on feedback
  README.md
  tutorials/install.md
Labels: documentation, beta, 🎵 harmonic

#231 Prepare for 6.1.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#232 Merge: 6 -> 7
  Changelog.md
Labels: 🎵 harmonic

#233 Prepare for 7.0.0~pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#234 Prepare for 7.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
