Repository gazebosim/gz-launch, pull requests merged in 2023-08, with the labels that each got.

#226 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#227 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden

#224 Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-launch7
  .github/ci/packages.apt
  src/cmd/CMakeLists.txt
Labels: beta, 🎵 harmonic

#223 Removed Ignition
  Migration.md
  examples/factory.gzlaunch
  examples/multi_factory.gzlaunch
  include/CMakeLists.txt
  include/ignition/launch.hh
  include/ignition/launch/Export.hh
  include/ignition/launch/Plugin.hh
  include/ignition/launch/config.hh
  plugins/sim_factory/SimFactory.hh
  src/Manager.cc
  src/Manager_TEST.cc
  test/integration/deprecated_TEST.cc
  tutorials/install.md
Labels: beta, 🎵 harmonic

#228 Merge 6 -> main
  .github/workflows/triage.yml
  plugins/sim_factory/SimFactory.hh
Labels: 🎵 harmonic
