Repository gazebosim/gz-launch, pull requests merged in 2024-05, with the labels that each got.

#249 Add package.xml, remove dependency on python3-yaml, and disable failing windows tests
  .github/ci/packages.apt
  .github/workflows/package_xml.yml
  package.xml
  src/Manager_TEST.cc
Labels: 🎵 harmonic

#255 Disable failing windows tests
  src/CMakeLists.txt
  src/Manager_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdlaunch.rb.in
Labels: 🏯 fortress

#258 Fix windows warnings (#199)
  plugins/joy_to_twist/JoyToTwist.cc
  plugins/joy_to_twist/JoyToTwist.hh
  src/Manager.hh
  src/vendor/backward.hpp
Labels: 🏯 fortress

#262 Fix msvc warning (#250)
  src/Manager.cc
Labels: 🏯 fortress

#260 Disable cmdline tests on homebrew
  src/CMakeLists.txt
  src/ign_TEST.cc
Labels: 🏰 citadel

#264 Disable failing Manager_Test on windows
  src/Manager_TEST.cc
Labels: 🌱 garden

#263 Supress msvc dll exported interface warning
  src/CMakeLists.txt
  src/Manager.hh
  src/cmd/CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: 🏯 fortress

#265 Remove indirect dependencies
  .github/ci/packages.apt
  CMakeLists.txt
  package.xml
Labels: 🎵 harmonic

#266 Fix msvc loss of data warning
  plugins/sim_factory/SimFactory.cc
Labels: 🏛️ ionic
