Repository gazebosim/gz-launch, pull requests merged in 2025-02, with the labels that each got.

#287 Prepare for 7.1.1 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#289 Prepare for 8.0.1 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🏛️ ionic

#290 Merge 8 -> main
  Changelog.md
  plugins/websocket_server/WebsocketServer.cc
Labels: 🪵 jetty
